### ISSUE TITLE
Error with airbrake:deploy

### ISSUE THREAD

**Issue by nysthee** [airbrake/airbrake#421] opened 2015-09-30 17:19 UTC
#### Issue Type:
Bug Report

#### Airbrake Gem Version:

4.3.1
#### Ruby Version:

2.2.2
#### Framework Name/Version:

Rails 4.2.1
#### Airbrake Configuration:

```
  Airbrake.configure do |config|
    config.api_key = 'secret-string'
    config.host    = 'something-something'
    config.port    = 443
    config.secure  = config.port == 443
  end
```

#### Environment Name:
 -Production

#### Summary:

We are getting this error lately. The error is raised when deploying (we use airbrake/capistrano) and when running the rake task (see above) directly

#### Steps To Reproduce:

RAILS_ENV=production bin/rake airbrake:deploy TO=production

#### Expected Results:

successful execution of the rake task 
 
#### Actual Results:

```
sock@sock-001:~/sock$ RAILS_ENV=production bin/rake airbrake:deploy TO=production
rake aborted!
Net::ReadTimeout: Net::ReadTimeout
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent.rb:431:in `disable_all_tracing'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/cross_app_tracing.rb:41:in `tl_trace_http_request'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent.rb:431:in `disable_all_tracing'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/airbrake-4.1.0/lib/airbrake_tasks.rb:57:in `deploy'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/airbrake-4.1.0/lib/airbrake/shared_tasks.rb:16:in `block (2 levels) in <top (required)>'
OpenSSL::SSL::SSLErrorWaitReadable: read would block
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent.rb:431:in `disable_all_tracing'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/cross_app_tracing.rb:41:in `tl_trace_http_request'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent.rb:431:in `disable_all_tracing'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/newrelic_rpm-3.13.2.302/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/airbrake-4.1.0/lib/airbrake_tasks.rb:57:in `deploy'
/home/sock/apps/sock/shared/bundle/ruby/2.2.0/gems/airbrake-4.1.0/lib/airbrake/shared_tasks.rb:16:in `block (2 levels) in <top (required)>'
Tasks: TOP => airbrake:deploy
(See full trace by running task with --trace)
```

**Comment by kyrylo** [comment] 2015-09-30 19:41
Hello, @nysthee! Could you please update the gem to the recent version (4.3.1) and try again? I'm not sure it will fix the issue, but it's worth a try.

**Comment by nysthee** [comment] 2015-10-01 22:35
Hey @kyrylo, updating the gem didn't fix the error.

**Comment by shifi** [comment] 2015-10-02 00:45
Hi @nysthee 
Can you please update your issue according to [this guidelines](https://github.com/airbrake/airbrake/blob/master/CONTRIBUTING.md) so we can try to reproduce it.
Thank you.

**Comment by nysthee** [comment] 2015-10-02 07:52
Done. Sorry I didn't do this in the first place.

**Comment by shifi** [comment] 2015-10-03 01:43
Thank you. I will try to reproduce it.

**Comment by shifi** [comment] 2015-10-03 05:29
@nysthee I'm having hard time reproducing this :disappointed: 
When did you notice this issue? After upgrading to new ruby/rails/airbrake version?
Please provide me with any additional info you think would be helpful.

**Comment by nysthee** [comment] 2015-10-03 10:20
Actually this happened after updating the errrbit backend we are reporting to. On that side though the api call gives a 200 response.

**Comment by joren** [comment] 2015-11-05 14:30
I think the problem is with the method 'tore_cached_attributes_on_problems' that is taking very very very long and makes the request timeout.

I'm figuring out why it takes so long

**Comment by kyrylo** [comment] 2015-11-06 03:23
I'm not sure we have this method in our library.

**Comment by joren** [comment] 2015-11-06 07:59
I'm so sorry, the problem is Errbit. 
You can close this issue.

**Closed** 2015-11-06 08:32 UTC

**Comment by kyrylo** [comment] 2015-11-06 14:03
No worries. Feel free to reopen if you think it's our problem :)
