### ISSUE TITLE
ActiveJob using DelayedJob notifies Airbrake twice

### ISSUE THREAD

**Issue by adamlangsner** [airbrake/airbrake#608] opened 2016-10-07 19:40 UTC
I'm using Airbrake v5.5.0 in a rails app. I wanted to test out error handling in my delayed jobs so I made a Job like this:

``` rb
class RaiseyMcRaiseJob < ActiveJob::Base
  def perform
    raise "I'm a bad piece of code"
  end
end
```

I enqueued it on my staging environment and noticed that 2 errors were showing up every time the job ran. (side note: the bucketing still worked, i.e. after running the job 3 times I had 2 errors with 3 occurrences each)

I think ActiveJob and Airbrake are both handling the error. As a quick fix I added this to my `config/initializers/airbrake.rb`

``` rb
Delayed::Worker.plugins = Delayed::Worker.plugins.reject do |plugin|
  plugin == Delayed::Plugins::Airbrake
end
```

This way ActiveJob handles the error and it only shows up once in airbrake. This is a hacky solution and maybe I'm doing something wrong?

I'm happy to open a PR with some changes. Maybe Airbrake can check to see if ActiveJob is being used and not add the plugin to the `plugins` array?

**Comment by adamlangsner** [comment] 2016-10-10 16:14
@kyrylo is this in fact a bug and not user error on my part?

**Comment by kyrylo** [comment] 2016-10-10 16:33
>  is this in fact a bug and not user error on my part?

It's not a bug, but rather an issue with ActiveJob. I've tried to reproduce the described behaviour and found out that if you configure your ActiveJob adapter it sends only one error.

```
# config/applicaiton.rb
config.active_job.queue_adapter = :delayed_job
```

Do you configure your adapter? If not, could you try to configure it as shown?

**Comment by adamlangsner** [comment] 2016-10-10 16:43
@kyrylo weird, I do have that line in my `application.rb`

**Comment by kyrylo** [comment] 2016-10-10 16:46
Ok, if that's not too hard for you, could you setup a basic repository demonstrating the issue (so we are on the same page)? It will greatly simplify debugging for me.

**Comment by adamlangsner** [comment] 2016-10-10 16:47
@kyrylo sounds good. I can do that

**Comment by kyrylo** [comment] 2016-10-11 14:23
Could you give me an ETA? I am really close to releasing another MINOR version of the gem and this is currently the only thing that blocks the release. No rush, but would be nice to know, still.

**Comment by adamlangsner** [comment] 2016-10-11 14:43
@kyrylo I'm going to try and get to this by the end of the week. I don't think you should hold up a release for this since we still haven't confirmed that it is indeed a legit bug.

**Comment by adamlangsner** [comment] 2016-10-13 19:05
@kyrylo I've created a test app to replicate the issue I'm seeing. I've deployed the app and an errbit instance to heroku so that you can play around with it.

If you go to https://fathomless-scrubland-42664.herokuapp.com/ you can fill out that form and it will enqueue a `RaiseJob` and that job will raise whatever message you put in the text field. then you can go to errbit: https://airbrakedjtest-errbit.herokuapp.com and login by clicking the "Sign in with Github" button. I've added an errbit user with your github info so you should be able to login to errbit no problem (I've configure the errbit github oauth to have minimum permissions on github so that it only has access to your public info and not any of your public/private repos)
You'll see in errbit that there are two error buckets for each error.

This is the repo for the app: https://github.com/spruceholdings/airbrakedjtest
and here's the commit with all the relevant configuration and code: https://github.com/spruceholdings/airbrakedjtest/commit/fc2aaf0c6a326dc64a6f52d59a4e4e0c487774c7

I hope I've set everything up correctly to make it easy for you to debug, let me know if you have any questions

**Comment by kyrylo** [comment] 2016-10-17 15:17
Thanks for the detailed description and the repo, it was indeed really helpful!

I came to conclusion that this is probably the best way to avoid duplicates, if you dislike them:

```rb
Airbrake.add_filter do |notice|
  if notice[:context][:action] == 'ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper'
    notice.ignore!
  end
end
```

I am going to add this information to the README and close this issue. I don't think it's a bug, so I am removing the corresponding label.

**Comment by kyrylo** [comment] 2016-10-17 15:23
I forgot to add, if it's possible for you, please don't delete the repository. I might need it in the future.

**Comment by adamlangsner** [comment] 2016-10-17 17:34
@kyrylo Thanks for taking a look. That filter should do the trick. Happy to keep the repo open, do you think there will be more work done in this area in a future release? No rush on our end, just curious.

**Comment by kyrylo** [comment] 2016-10-17 22:12
So far the filter should do the job. As of now, I don't see what else we can do here.

**Comment by kreintjes** [comment] 2017-04-10 10:41
Note: same problem occurs when using Sidekiq and can probably be fixed the same way, but then using `ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper` in the filter instead of `ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper`. Testing that now.

**Comment by kreintjes** [comment] 2017-04-19 15:36
In another project I was still using Airbrake 5.4.5 and Airbrake-Ruby 1.5.0 (and Sidekiq 4.1.4). There the fix from the README was working. However, after updating Airbrake and Sidekiq it stopped working as well. Eventually I fixed it by adding the following filter:

```
Airbrake.add_filter do |notice|
  # Do not notify about exceptions triggered by ActiveJob, since these are also being triggered by Sidekiq itself.
  notice.ignore! if notice[:context][:component] == 'active_job'
end
```

Figuring every ActiveJob is performed by Sidekiq, so every exception in ActiveJob is notified by Airbrake's Sidekiq integration. @kyrylo if you would like I could update the readme.

**Comment by mgodwin** [comment] 2017-08-16 16:19
Nice work @kreintjes.  I noticed the same behavior in my Rails 5/sidekiq5 project as well.  The README example does not de-duplicate error messages any longer.  Ignoring active job and falling back to sidekiq looks like a decent approach for the time being.  

However, I'm annoyed this just changed silently though, and the "solution" here seems kind of janky.  Can we get an explanation as to what the `context` is and why it's different for the two errors?  _Why_ do I have to do this in the first place?

**Comment by kyrylo** [comment] 2017-09-11 16:40
> @kreintjes 
> [...] Or even nicer would be to disable AIrbrake's ActiveJob integration when it detects Sidekiq or DelayedJob. Not sure how to do that though.

I think the library could include a filter similar to the one that you shared, so users don't have to do anything. I'll look what else I can do, but this solution seems to be most obvious so far.

> mgodwin
> Can we get an explanation as to what the context is and why it's different for the two errors? Why do I have to do this in the first place?

We register two hooks: for ActiveJob and Sidekiq. Whenever an exception happens, both of those hooks get fired. I need to read about ActiveJob more to understand why it lets exceptions bubble up to find the best solution.

**Closed** 2017-09-20 20:14 UTC
Labels: ActiveJob, DelayedJob
