### ISSUE TITLE
Add support for HTTP_X_FORWARDED_FOR as "remote ip"

### ISSUE THREAD

**Issue by jensb** [airbrake/airbrake#471] opened 2016-01-10 08:33 UTC
If an application sits behind reverse proxies, Airbrake's dashboard always reports the proxy IP addresses as "Remote IP" - which is hardly helpful.

Airbrake should parse HTTP_X_FORWARDED_FOR if it exists and if the first IP in this list matches a predefined IP list or range or network (maybe configurable in the client) this IP should be used as "Remote IP" for display in the dashboard instead of REMOTE_ADDR.

**Comment by vmihailenco** [comment] 2016-01-10 11:29
We already check
1. X-Forwarded-For
2. X-Real-Ip
3. remote address of the client

My guess is that `X-Forwarded-For` header contains "Remote IP" string. I am not sure what we have to do in such case.

**Comment by kyrylo** [comment] 2016-01-12 12:21
Seems to be a duplicate of https://github.com/airbrake/airbrake/issues/266.

**Closed** 2016-01-14 11:40 UTC
Labels: Question
