### ISSUE TITLE
Airbrake sends POST body on error

### ISSUE THREAD

**Issue by mheffner** [airbrake/airbrake#182] opened 2013-02-06 04:18 UTC
It would be really convenient if Airbrake could send the contents of the POST body when generating an exception. In our application scenario, the JSON body has the important payload details that would help us track down why certain requests fail. I don't see a way to enable that for Airbrake?

Extra points if it could detect the posted content type (eg, application/json), and render the body in the correct formatting at the exception handler interface.

We are using airbrake version 3.1.6 with the self-hosted errbit project.

**Comment by kyrylo** [comment] 2015-10-16 17:38
Hello, everyone!

Are people still interested in this? I am happy to work on this.

If this is still useful for you guys, then I would like to clarify how everyone sees this implemented. Do you want to see a new tab in the dashboard (for example, "Raw"), that would display unparsed error reports (with syntax highlighting)?

If no-one is interested anymore, I will have to close this issue.

**Comment by mheffner** [comment] 2015-10-23 12:14
We don't use the project anymore, but IMO this is still important to have. It largely means that any request that accepts parameters in a POST body can not be replayed for testing.

**Comment by kyrylo** [comment] 2015-10-23 13:24
@mheffner thanks for the answer. Is my understanding if this issue correct?

**Comment by mheffner** [comment] 2015-10-23 13:47
@kyrylo Well, I haven't used the product in a while so I couldn't comment on the UI questions. IMO the POST bodies should be visible near by where the parameters for a GET request would be displayed.

**Comment by tiagomatos** [comment] 2015-11-02 21:34
As @mheffner stated, this is really important while debugging our API.
Would be great to visualize the body from PUT and POST requests (which hold the JSON payload).

**Comment by kyrylo** [comment] 2015-11-03 03:01
@tiagomatos let me just clarify this. Do you want to see the body of requests that caused an exception? That is, you made a POST request with some payload and it crashed your app, and the problem is that Airbrake doesn't display that (potentially) faulty body, it only says that it was a POST request. Is my understanding correct?

**Comment by tiagomatos** [comment] 2015-11-03 12:39
@kyrylo yes. When there's an exception with a POST / PUT request we can only see the params from the URL query strings but would be great if we could see the cause of the error. Which 99% of time is on the JSON payload at the request.body.

**Comment by kyrylo** [comment] 2015-11-03 14:45
Thanks! This definitely looks useful. We plan a big release of this library and I'll make sure that we support this out-of-box.

**Comment by kyrylo** [comment] 2015-11-13 05:07
@tiagomatos I just double checked everything and from my understanding we actually already support this :)

I've made this request:

```
curl -v -X POST -H "Content-Type: application/json" -d '{"environment":"production","username":"john","repository":"https://github.com/airbrake/airbrake","revision":"38748467ea579e7ae64f7815452307c9d05e05c5","version":"v2.0"}' "localhost:3000/crash"
```

And I got this report in my dashboard:

![screenshot29](https://cloud.githubusercontent.com/assets/1079123/11139184/ef1c2516-89d4-11e5-9e3d-0cdd06160fa4.png)

It looks like all the params are there and we already support POST request params. Please let me know if you guys imply something else.

**Comment by kyrylo** [comment] 2015-11-16 17:57
Please ping me if you believe this is not fixed. Thanks!

**Closed by kyrylo** 2015-11-16 17:57 UTC
Labels: feature

**Comment by halida** [comment] 2016-10-21 02:29
Hi, If the payload is failed, like the request post body is an XML, and XML is not valid, Rails ParamsParser will raise an Error. For this case, Airbrake cannot get Params, and display it.
So I think we should open this issue again.

**Comment by halida** [comment] 2016-10-21 07:56
@kyrylo

**Comment by halida** [comment] 2016-10-21 08:45
@kyrylo Please see the merge request: https://github.com/airbrake/airbrake/pull/621
It is the modified version for my project, you can make it as an reference and close it.

**Comment by kyrylo** [comment] 2016-10-21 13:49
If you can provide payload which makes Airbrake crash, then I could write a test for this case.

**Comment by kyrylo** [comment] 2016-10-21 13:50
By the way, @halida, it seems like you are using Airbrake v4. It's going to be unmaintained in 1 month.

**Comment by halida** [comment] 2016-10-21 14:10
@kyrylo Yes, like this:

```ruby
require 'rest_client'
r = RestClient::Resource.new 'localhost:3000'
response = r["/testing"].post("<tag1>text</tag2>", :content_type => "text/xml")
```

Post failed XML format will raise an error, and because rails cannot parse this xml, it cannot be record by airbrake.

**Comment by kyrylo** [comment] 2016-10-21 15:37
Thanks, the issue seems to be related to XML requests in general. I filed a new issue: https://github.com/airbrake/airbrake/issues/623
