### ISSUE TITLE
NoMethodError: undefined method `call' for nil:NilClass

### ISSUE THREAD

**Issue by nick-desteffen** [airbrake/airbrake#490] opened 2016-01-20 15:55 UTC
* Airbrake version: 5.0.3
* Ruby version: 2.2.2
* Framework name & version: Rails 4.2.5

#### Airbrake config

```ruby
Airbrake.configure do |config|
  config.environment = Rails.env
  config.ignore_environments = %w(development test)
  config.project_key = 'XXXXXXXXX'
  config.project_id = XXXXX
end

filters_to_ignore = [
  "EventPublicationError"
]

Airbrake.add_filter do |notice|
  if notice[:errors].any? { |error| filters_to_ignore.include?(error[:type]) }
    notice.ignore!
  end
end
```

#### Description

All of our applications keep getting this exception.  We aren't sure where it is coming from, the only information of use is on the context tab within Airbrake web application.

How can we go about stopping these?

Here is the context tab:

```json
{
  "environment": "production",
  "language": "ruby/2.2.2",
  "notifier": {
    "name": "airbrake-ruby",
    "url": "https://github.com/airbrake/airbrake-ruby",
    "version": "1.0.3"
  },
  "os": "x86_64-linux",
  "remoteAddr": "XX.XXX.XXX.XXX"
}
```

**Comment by kyrylo** [comment] 2016-01-20 15:59
Thanks for the report. We are aware of this issue. It was supposed to be fixed by https://github.com/airbrake/airbrake-ruby/pull/21, but apparently it didn't work out.

**Comment by nick-desteffen** [comment] 2016-01-20 16:04
No problem.  I was hoping that updating `airbrake-ruby` to 1.0.3 would fix it as well, but we just deployed last night and we are still getting thousands of these errors.  Everything seems to be working fine though.

**Comment by kyrylo** [comment] 2016-01-20 16:09
Sorry about that, it's hard to debug this. This is super high on my priority list.

**Comment by kyrylo** [comment] 2016-01-21 13:33
@nick-desteffen do you use Passenger?

**Comment by nick-desteffen** [comment] 2016-01-21 14:49
Yes we do, version 5.0.11

**Comment by kyrylo** [comment] 2016-01-22 13:52
I've been debugging this very thoroughly and came to the conclusion that it's a bug in Passenger. Unfortunately I don't know where exactly. I skimmed through the Passenger code and tried to debug that, but my knowledge of Passenger's internals is limited.

Here's the proof. Given this Sinatra app...

```ruby
require 'sinatra'

at_exit do
  puts 'CONFIG.RU AT_EXIT'
  if $!
    puts "EXITING BECAUSE OF AN EXCEPTION:"
    p $!
    p $!.backtrace
  end
end

get '/' { 'Hello world!' }
run Sinatra::Application
```

...launch it with `passenger start`. Then make a few requests and wait for 5 minutes. When 5 minutes passed check your console and evidence this:

```
App 8923 stdout: CONFIG.RU AT_EXIT
[ 2016-01-22 15:01:45.3458 8875/7f3ae0e58700 age/Cor/CoreMain.cpp:794 ]: Disconnecting long-running connections for process 12434, application /home/kyrylo/code/airbrake-passenger-demo/public (development)
App 12434 stdout: CONFIG.RU AT_EXIT
App 12434 stdout: EXITING BECAUSE OF AN EXCEPTION:
App 12434 stdout: #<NoMethodError: undefined method `call' for nil:NilClass>
App 12434 stdout: []
[ 2016-01-22 15:01:50.2792 8875/7f3ae0e58700 age/Cor/CoreMain.cpp:794 ]: Disconnecting long-running connections for process 10205, application /home/kyrylo/code/airbrake-passenger-demo/public (development)
App 10205 stdout: CONFIG.RU AT_EXIT
App 10205 stdout: EXITING BECAUSE OF AN EXCEPTION:
App 10205 stdout: #<NoMethodError: undefined method `call' for nil:NilClass>
App 10205 stdout: []
```

As you can see this error comes from Passenger and Airbrake simply reports it (instead of reporting we log the error in this app). Thus I am 101% sure it's not an issue with Airbrake.

What this means to you? I am going to file an issue at Passenger's issue tracker and you should probably follow it. Until the issue is resolved I'd suggest to ignore this particular error:

```ruby
Airbrake.add_filter do |notice|
  # See: https://github.com/airbrake/airbrake/issues/490
  passenger_error = proc do |error|
    error[:backtrace].empty? && error[:type] == 'NoMethodError'
  end

  notice.ignore! if notice[:errors].any?(&passenger_error)
end
```

Thanks for the report.

**Closed by kyrylo** 2016-01-22 13:52 UTC
Labels: Question

**Comment by kyrylo** [comment] 2016-01-22 13:59
Filed the issue: https://github.com/phusion/passenger/issues/1730.

**Comment by svoop** [comment] 2016-01-22 14:01
Nice work, thanks a bunch once again, @kyrylo!

**Comment by nick-desteffen** [comment] 2016-01-22 14:29
Awesome, thanks for your help @kyrylo, we appreciate it.

**Comment by J-Zet** [comment] 2016-01-22 14:49
Well done! Thanks from my side aswell @kyrylo

**Comment by kyrylo** [comment] 2016-01-22 14:51
Aww :heart: :) Happy Airbraking/Errbitting!

**Comment by andrewdollard** [comment] 2016-01-22 18:24
Thank you!

**Comment by kyrylo** [comment] 2016-01-26 14:12
This was fixed by https://github.com/phusion/passenger/commit/4f898b0a7906c174f21a2c1eddd9e2e86e07cc1f.
