### ISSUE TITLE
"stack level too deep" error after updating from 9.3.0 to 11.0.1

### ISSUE THREAD

**Issue by maldad** [airbrake/airbrake#1141] opened 2020-12-23 07:32 UTC
Hi there, we have a problem after upgrading the Airbrake gem, it seems like it has a conflict with Capybara config.

This only happens when we run capybara tests, our controller or helper tests are good, here is the Gemlock changelog:

Before the error:
```
airbrake (9.3.0)
      airbrake-ruby (~> 4.5)
    airbrake-ruby (4.5.0)
```

After:
```
airbrake (11.0.1)
      airbrake-ruby (~> 5.1)
    airbrake-ruby (5.2.0)
```

Looking at the logs I've found the next pattern:

```
1.1) Failure/Error: bridge = driver.browser.send(:bridge)

SystemStackError:
  stack level too deep

# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack/request_store.rb:14:in `store'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack/request_store.rb:24:in `[]'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:23:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
# /home/agus/.rvm/gems/ruby-2.6.6/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'

  This pattern continues for a while...
```

The problem seems to lie on this statement that we have on our Capybara config file:

`bridge = driver.browser.send(:bridge)`

Before upgrading, that `driver.browser` returned this:

```
[1] pry(main)> driver
=> #<Capybara::Selenium::Driver:0x000055dde8d65530
 @app=
  #<Rack::Builder:0x000055dde8b1f578
   @freeze_app=false,
   @map={"/"=>#<Proc:0x000055dde8b1f460@/home/agus/.rvm/gems/ruby-2.6.6/gems/actionpack-6.0.3.3/lib/action_dispatch/system_test_case.rb:139>},
   @run=nil,
   @use=[],
   @warmup=nil>,
 @browser=nil,
 @exit_status=nil,
 @frame_handles={},
 @node_class=Capybara::Selenium::Node,
 @options=
  {:browser=>:chrome,
   :clear_local_storage=>nil,
   :clear_session_storage=>nil,
   :options=>
    #<Selenium::WebDriver::Chrome::Options:0x000055dde8d66110
     @args=
      #<Set: {"--headless", "--no-sandbox", "--disable-extensions", "--disable-gpu", "--disable-popup-blocking", "--disable-dev-shm-usage", "--window-size=1366,768"}>,
     @binary=nil,
     @detach=nil,
     @emulation={},
     @encoded_extensions=[],
     @extensions=[],
     @options={},
     @prefs=
      {:download=>{:directory_upgrade=>true, :prompt_for_download=>false, :default_directory=>#<Pathname:/home/agus/repos/web_punch/tmp/downloads>},
       :browser=>{:set_download_behavior=>{:behavior=>"allow"}}},
     @profile=nil>}>

[2] pry(main)> driver.browser
=> #<Selenium::WebDriver::Chrome::Driver:0x..fc28561bc571f4812 browser=:chrome>
```

Any help is appreciated, thanks in advance.

**Comment by kyrylo** [comment] 2020-12-23 12:20
I can see that you use Skylight. To make the experiment clear, could you uninstall Skylight and run the tests again?

**Comment by maldad** [comment] 2020-12-23 14:07
Sure, I can do it, I'll keep you posted.

**Comment by maldad** [comment] 2021-01-04 22:26
Hi there @kyrylo, sorry for the late response, we went on vacation, but now we are back.

I uninstalled Skylight and now my tests that use Capybara run smoothly, could this be a problem with the Skylight config?

**Comment by rvalladares77** [comment] 2021-01-07 21:06
I am getting a similar problem "`SystemStackError: stack level too deep`" but in my case I use Solr for search and when I try to reindex a model  I get this:

```
rake aborted!
SystemStackError: stack level too deep
/home/bobyvalla/bundle/ruby/2.5.0/gems/airbrake-11.0.1/lib/airbrake/rack.rb:21:in `capture_timing'
/home/bobyvalla/bundle/ruby/2.5.0/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/mini_profiler/profiling_methods.rb:46:in `step'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/patches/net_patches.rb:18:in `request_with_mini_profiler'
/home/bobyvalla/bundle/ruby/2.5.0/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
/home/bobyvalla/bundle/ruby/2.5.0/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
/home/bobyvalla/bundle/ruby/2.5.0/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/mini_profiler/profiling_methods.rb:46:in `step'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/patches/net_patches.rb:18:in `request_with_mini_profiler'
/home/bobyvalla/bundle/ruby/2.5.0/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:11:in `block in request'
/home/bobyvalla/bundle/ruby/2.5.0/gems/airbrake-11.0.1/lib/airbrake/rack.rb:25:in `capture_timing'
/home/bobyvalla/bundle/ruby/2.5.0/gems/airbrake-11.0.1/lib/airbrake/rails/net_http.rb:10:in `request'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/patches/net_patches.rb:19:in `block in request_with_mini_profiler'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/mini_profiler/profiling_methods.rb:46:in `step'
/home/bobyvalla/bundle/ruby/2.5.0/gems/rack-mini-profiler-2.3.0/lib/patches/net_patches.rb:18:in `request_with_mini_profiler'

```


This problem started when I upgraded airbrake (10.0.5) to airbrake (11.0.1)

```
Git diff:
-    airbrake (10.0.5)
-      airbrake-ruby (~> 4.13)
-    airbrake-ruby (4.15.0)
+    airbrake (11.0.1)
+      airbrake-ruby (~> 5.1)
+    airbrake-ruby (5.2.0)

```

**Comment by kyrylo** [comment] 2021-01-08 10:35
This is a duplicate of https://github.com/airbrake/airbrake/issues/1089.

@rvalladares77 in your case `rack-mini-profiler` is the issue: https://github.com/MiniProfiler/rack-mini-profiler/issues/437

I would suggest to upgrade `skylight` and `rack-mini-profiler`.

**Closed by kyrylo** 2021-01-08 10:35 UTC
