### ISSUE TITLE
SystemStackError:stack level too deep exceptions not being sent to Airbrake

### ISSUE THREAD

**Issue by joevandyk** [airbrake/airbrake#395] opened 2015-06-25 17:10 UTC
I saw the following in my logs:

```
method=POST path=/admin/drop_shippers format=html controller=admin/drop_shippers action=create status=500 error='SystemStackError:stack level too deep' duration=21.39 db=6.68
** [Airbrake] Failure: Net::HTTPRequestEntityTooLarge
```

So we had a bug that resulted in an infinite loop. It looks like the exception wasn't being sent to airbrake because the stacktrace was too big. Maybe the stacktrace should be capped at a maximum limit? Or the limit should be raised to a higher amount.

**Comment by shifi** [comment] 2015-06-26 01:48
Maximum size of notice we accept is 64kb.
The problem is that stacktrace is not the only thing which could overfill notice size.
There are other things such as params, sessions, cgi_data so it's hard to know where to reduce the size.

**Comment by joevandyk** [comment] 2015-06-26 02:52
Yeah. But maybe if the exception is one of this type, only the last, say, 30kb of the stack trace are submitted?

As is, none of these errors will make it to airbrake.

**Comment by shifi** [comment] 2015-06-27 01:58
We will consider implementing this in major version. Thanks

**Comment by kyrylo** [comment] 2015-11-11 03:49
This issue is fixed in the new upcoming major release. We truncate notices bigger than 64KB. The strategy to truncation is quite flexible (and non-deterministic). So, we truncate everything that can be truncated, including stack frames.

**Closed by kyrylo** 2015-11-11 03:49 UTC
Labels: feature

**Comment by joevandyk** [comment] 2015-11-11 16:56
Awesome.
