### ISSUE TITLE
Airbrake 9.5.5 update Error: config.query_stats = false is not working

### ISSUE THREAD

**Issue by Vigneshwar2411** [airbrake/airbrake#1057] opened 2020-01-06 11:18 UTC
Airbrake version: 9.5.5
Airbrake-Ruby: 4.11.1
Ruby version: 2.6.4
Rails version: 5.2.3

Description:
When upgraded to Airbrake 9.5 version, my local rails application is not starting up. It is throwing an error as shown in the below log.

When I traced it into the Airbrake gem file, query_stats is always true as per documentation. And on the airbrake>rails>railtie.rb: 115, it throws Active Record connection error. 

Error Log below, 

```
=> Booting Puma
=> Rails 5.2.3 application starting in apollo_mr_cooper_development
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	65: from bin/rails:3:in `<main>'
	64: from bin/rails:3:in `load'
	63: from /Users/vignesh/Documents/workspace/apollo/apollo-web/bin/spring:15:in `<top (required)>'
	62: from /Users/vignesh/Documents/workspace/apollo/apollo-web/bin/spring:15:in `require'
	61: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
	60: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
	59: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	58: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	57: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	56: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
	55: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
	54: from /Users/vignesh/Documents/workspace/apollo/apollo-web/bin/rails:9:in `<top (required)>'
	53: from /Users/vignesh/Documents/workspace/apollo/apollo-web/bin/rails:9:in `require'
	52: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
	51: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	50: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	49: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	48: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	47: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	46: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
	45: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
	44: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	43: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:53:in `start'
	42: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/server.rb:283:in `start'
	41: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	40: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:27:in `app'
	39: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	38: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	37: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	36: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	35: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	34: from config.ru:in `<main>'
	33: from config.ru:in `new'
	32: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	31: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	30: from config.ru:3:in `block in <main>'
	29: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	28: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	27: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	26: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	25: from /Users/vignesh/Documents/workspace/apollo/apollo-web/config/environment.rb:5:in `<top (required)>'
	24: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
	23: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
	22: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	21: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	20: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	19: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `call'
	18: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:347:in `each'
	17: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	16: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	15: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	14: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	13: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	12: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
	11: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
	10: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/airbrake-9.5.5/lib/airbrake/rails/railtie.rb:96:in `block in <class:Railtie>'
	 9: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
	 8: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:42:in `each'
	 7: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
	 6: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
	 5: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
	 4: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
	 3: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
	 2: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/airbrake-9.5.5/lib/airbrake/rails/railtie.rb:115:in `block (2 levels) in <class:Railtie>'
	 1: from /Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:110:in `connection_config'
/Users/vignesh/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/connection_handling.rb:114:in `connection_pool': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)

Do you have any ideas?

**Comment by kyrylo** [comment] 2020-01-07 07:29
I tried a new Rails app and confirmed that `query_stats = false` *does* work. No queries are being sent to Airbrake when it's off.

We had a similar report last year https://github.com/airbrake/airbrake/issues/1022
Are sure your `airbrake.rb` initializer gets loaded? My hunch is that it doesn't and therefore your modification to the config is never run.

**Comment by Vigneshwar2411** [comment] 2020-01-07 11:49
@kyrylo I have 'activerecord-nulldb-adapter' installed. Is that because of that which is causing the AR connection error?

**Comment by kyrylo** [comment] 2020-01-08 04:44
I tried installing `activerecord-nulldb-adapter` in my fresh Rails project and it works fine. I noticed when I use this adapter, no SQL queries are being made at all.

What if you set [`config.performance_stats = false`](https://github.com/airbrake/airbrake-ruby#performance_stats)?

**Comment by kyrylo** [comment] 2020-01-13 04:13
My hunch still remains the same: the `airbrake.rb` initializer is never loaded. 
Since I cannot reproduce this issue and there's no additional feedback, I'm closing it. That said, don't be afraid to ask/clarify here.

**Comment by srpatel** [comment] 2020-01-21 10:57
We are having the same issue. I am sure the query stats are still being sent, as a breakpoint in `ActiveRecordSubscriber.call` is getting hit.

After investigation, it is due to the order in which the initialisers run. You can run `rake initializers` to confirm this. If `Airbrake::Rails::Railtie.airbrake.middleware` (and family) appear before your application's `Application.load_config_initializers`, you will reproduce the issue.

I think the issue should be re-opened, with one possible fix being to use the `:after` option in the railtie:
```
initializer('airbrake.middleware', after: :load_config_initializers) do |app|
    ...
end
```

As a workaround for anyone affected by this issue, you can define an initialiser in your Application config rather than in the `initializers` folder, and specify that it should run before Airbrake's initialiser:

```
class Application < Rails::Application
  initializer 'airbrake-config', before: 'airbrake.middleware' do
    Airbrake.configure do |config|
      # ...
      config.performance_stats = false
      config.query_stats = false
    end
  end
  # ...
end
```

**Comment by kyrylo** [comment] 2020-01-28 07:55
@srpatel thanks for digging into this. The fix sounds sensible to me.

**Closed** 2020-01-28 09:14 UTC
Labels: Bug
